### ISSUE TITLE
Sometimes the old uploaded files will lost

### ISSUE THREAD

**Issue by huacnlee** [nowa/carrierwave-upyun#27]
场景：

- 上传一张图， foo.jpg
- 一段时间以后，foo.jpg 异常丢失，但我确信是没有删除的动作

最早搞 IMAX.im 的时候就会遇到，到现在我依然没查到原因在哪里，现在我的另外一个项目里面再次遇到。

## 目前我的猜测

```ruby
class User
  mount_uploader :avatar, AvatarUploader
end
```

1. 我在怀疑是否有可能用户在修改数据（非修改 `:avatar` 字段），遇到 Bug，无意中触发了 Carrierwave 删除旧图片的功能？

2. 用户实际上是在修改 `:avatar`，Carrierwave 上传成功，并删除了旧图片。接着程序挂了，或执行步骤异常中断了，新的图片地址没有存入数据库。

----

第二个情况似乎比较容易发生。

**Comment by hzlu** [comment]
model update和destroy之后，又拍云上的图片没有被回调删除，model里面没有skip_callback，请问怎么处理这个问题
